Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/domain.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: 'OR('OrdererMSP.member')'
            Writers:
                Type: Signature
                Rule: 'OR('OrdererMSP.member')'
            Admins:
                Type: Signature
                Rule: 'OR('OrdererMSP.admin')'

    - &org1
        Name: org1MSP
        ID: org1MSP
        MSPDir: crypto-config/peerOrganizations/org1.domain.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: 'OR('org1MSP.admin', 'org1MSP.peer', 'org1MSP.client')'
            Writers:
                Type: Signature
                Rule: 'OR('org1MSP.admin', 'org1MSP.client')'
            Admins:
                Type: Signature
                Rule: 'OR('org1MSP.admin'
        AnchorPeers:
            - Host: peer0.org1.domain.com
            Port: 7051
    - &org2
        Name: org2MSP
        ID: org2MSP
        MSPDir: crypto-config/peerOrganizations/org2.domain.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: 'OR('org2MSP.admin', 'org2MSP.peer', 'org2MSP.client')'
            Writers:
                Type: Signature
                Rule: 'OR('org2MSP.admin', 'org2MSP.client')'
            Admins:
                Type: Signature
                Rule: 'OR('org2MSP.admin'
        AnchorPeers:
            - Host: peer0.org2.domain.com
            Port: 9051
Capabilities:
    Channel: &ChannelCapabilities
        V1_3: true
    Orderer: &OrdererCapabilities
        V1_1: true
    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Writers:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.domain.com:7050
    BatchTimeout: 2s
    BatchSize:"
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Writers:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Writers:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ApplicationCapabilities

Profiles:
    OrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *org1
                    - *org2
    OrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                    - *org1
                    - *org2
            Capabilities:
                <<: *ApplicationCapabilities
    SampleDevModeKafka:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: kafka
            Kafka:
                Brokers:
                - kafka.domain.com:9092
            Organizations:
            - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *org1
                    - *org2
    SampleMultiNodeEtcdRaft:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: orderer.domain.com
                Port: 7050
                ClientTLSCert: crypto-config/ordererOrganizations/domain.com/orderers/orderer.domain.com/tls/server.crt
                ServerTLSCert: crypto-config/ordererOrganizations/domain.com/orderers/orderer.domain.com/tls/server.crt
            Addresses:
                - orderer.domain.com:7050
            Organizations:
            - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *org1
                    - *org2
